apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
images:
- name: ghcr.io/dipakshimpi/wisecow
  newName: ghcr.io/dipakshimpi/wisecow
  newTag: sha-d31bbd67cf4a459226a30d29d99618632a4c392b
