apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
images:
- name: ghcr.io/dipakshimpi/wisecow
  newName: ghcr.io/dipakshimpi/wisecow
  newTag: sha-19d717a9e8877e79c35c1cdca8f9292542c1a8f2
