apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
images:
- name: ghcr.io/dipakshimpi/wisecow
  newName: ghcr.io/dipakshimpi/wisecow
  newTag: sha-7d5759834229d9dadaaf1422ffacbbf096455021
