apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wisecow-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/dipakshimpi/wisecow.git'
    path: k8s
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
